name: 'Hello World'
description: 'Greet someone'
inputs:
  REPOSITORY:
    description: Login to ECR registry
    required: true
  IMAGE_REPO_NAME: 
    description: The name of the ECR registry
    required: true
  IMAGE_TAG:
    description: The tag that builds the image with
    required: true
    default: latest

runs:
  using: "composite"
  steps:
  
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%Y%m%d%S)"
    -
      name: Build ECR image - Push to Amazon ECR Registry
      env:
        REPOSITORY: ${{ inputs.REPOSITORY }}
        IMAGE_REPO_NAME: ${{ inputs.IMAGE_REPO_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        COMMIT_HASH: ${{ inputs.COMMIT_HASH }}
        BUILD_TIMESTAMP: ${{ steps.timestamp.outputs.timestamp }}}
      run: |
        docker build --no-cache --build-arg REPOSITORY=$REPOSITORY -t $IMAGE_REPO_NAME:$IMAGE_TAG .
        docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY/$IMAGE_REPO_NAME:$IMAGE_TAG-$BUILD_TIMESTAMP
        docker push $REPOSITORY/$IMAGE_REPO_NAME:$IMAGE_TAG-$BUILD_TIMESTAMP
      shell: bash
